### ISSUE TITLE
Print out hints when unknown option is used in cmdline

### ISSUE THREAD

**Issue by gwei3** [01org/tpm2-tools#197]
It will be easier for user to get instant feedback on screen about what is wrong.

For example, better to change ./src/tpm2_listpcrs.c as below:

```
        case '?':
-            //              printf("Unknown Argument: %c\n",optopt);
+                          printf("Unknown Argument: %c\n",optopt);
            returnVal = -6;
            break;
```

**Comment by williamcroberts** [comment]
listpcrs is already done:

`        case ':':
            LOG_ERR("Argument %c needs a value!\n", optopt);
            goto error;
        case '?':
            LOG_ERR("Unknown Argument: %c\n", optopt);
            goto error;
        }`

 but I get what you're driving at. We'll leave this open until someone verifies all tools.
