### ISSUE TITLE
No tpm2.0-tools util that uses Tss2_Sys_Import

### ISSUE THREAD

**Issue by kamade** [01org/tpm2-tools#218]
The Intel TPM 2.0 TSS provides a Tss2_Sys_Import() routine,  inline with the TPM2_Import command in the TPM 2.0 specification, however there is presently no utility that leverages it. Such a utility would be useful for importing external key pairs into TPM

**Comment by williamcroberts** [comment]
So I am looking at this again, tpm2_load should do what you need. With that said,  however, import looks like it does the same thing as load, but supports encrypting the key.

See: https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf 13.3.2

**Comment by williamcroberts** [comment]
Closed in #435
