### ISSUE TITLE
tpm2_certify - improper serialization of data to disk

### ISSUE THREAD

**Issue by williamcroberts** [01org/tpm2-tools#229]
This code does not consider structure padding, and type endianess. This is a good canidate file for placing a header on or at least serializing properly.

`
    rc = saveDataToFile(ctx->sigFilePath, (UINT8 *) &signature,
            sizeof(signature));
    if (rc) {
        return false;
    }
`

**Comment by williamcroberts** [comment]
Some of this was fixed, some of it remains with TODO's marking them.

**Comment by liuqun** [comment]
#367 

In lib/files.h:
https://github.com/01org/tpm2.0-tools/commit/785d443396a8afdeb9b62f4f3d76545d22a7aa0c#diff-a57b2583fc6eb5f9c21e109490bf17d7

`bool files_save_tpm_context_to_file(TSS2_SYS_CONTEXT *sapi_context, TPM_HANDLE handle, const char *path);`
`bool file_load_tpm_context_from_file(TSS2_SYS_CONTEXT *sapi_context, TPM_HANDLE *handle, const char *path);`

The second API function was incorrectly re-named with prefix "file_", which should be "files_"
