### ISSUE TITLE
Add support for TPM2_EncryptDecrypt2

### ISSUE THREAD

**Issue by tonyespy** [01org/tpm2-tools#253]
According to the latest version of the TPM2 specification Part 3 - Commands [1], TPM2_EncryptDecrypt has been deprecated in favor of TPM2_EncryptDecrypt2, described in section 15.3 as follows:

This command is identical to TPM2_EncryptDecrypt(), except that the inData parameter is the first
parameter. This permits inData to be parameter encrypted.

This is being reported against release 1.1.0 of tpm2.0-tools.

[1] https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf

**Comment by flihp** [comment]
Don't disagree with this but to realize the benefit of EncryptDecrypt2 we'd need to support sessions. Migrating to the use of EncryptDecrypt2 is a good start. Figuring out how we want to deal with session integration is likely a larger topic.

**Comment by liuqun** [comment]
See also: https://github.com/01org/tpm2-tss/issues/506

**Comment by flihp** [comment]
This was resolved in 1fde3c308bd69e5c21d3c2ad43dae07aa06fe901
