### ISSUE TITLE
Update and improve the manual doc

### ISSUE THREAD

**Issue by martinezjavier** [01org/tpm2-tools#366]
The manual document has become outdated after all the recent developments in the last few months.

For example it still mentions the old (and now deleted) resourcemgr and doesn't talk about the new D-Bus based one.

And the same for the tools usage section, none of the new options are mentioned so there's a lot of work for the manual to catch up.

Also, IMHO the manual is not that easy to read. It seems to me that's duplicating a lot of the content already provided by the man pages. Instead, I think it would be good for new users to get something like a getting started document (maybe even giving some theory about TPMs) with practical use cases and a list of sample commands for each case.

There's already a lot of example commands in the manual but it would be good to explain the relation between them (i.e: that for sealing you need to create a primary key, then an object, use listpcrs and createpolicy if using a session auth, and so on).

**Comment by liuqun** [comment]
The following document provides a friendly usage manual about tpm2.0-tools.

https://www.infineon.com/dgdl/Infineon-TPM20_SLB6970-AN-v01_00-EN.zip?fileId=5546d4625acbae4c015ad6d953664083
(from Infineon's homepage)

I've got everything running yesterday. And I am using the legacy resourcemgr with the newest tpm2.0-tools. Just take with some tricks setting the following bash env:
```
export TPM2TOOLS_TCTI_NAME=socket
export TPM2TOOLS_SOCKET_ADDRESS=127.0.0.1
export TPM2TOOLS_SOCKET_PORT=2323
```

**Comment by martinezjavier** [comment]
@liuqun thanks a lot for the pointer.

**Comment by williamcroberts** [comment]
Make sure to address the switch to abrmd when discussing this, and probably add discussion about the in-kernel RM as well (since 4.12 IIRC).

**Comment by williamcroberts** [comment]
@martinezjavier @liuqun Maybe the better way of dealing with this is to kill of the "manual" doc, as it really just duplicates the man pages, and then work on the wiki?

I am also considering moving the man pages from groff to xml and use xmltoman, what's your experience with dealing and writing with man pages?

**Comment by martinezjavier** [comment]
@williamcroberts I agree with killing the manual doc. At least I found it confusing (and outdated) when first started learning about this project.

About your question, I don't think that xml is an improvement over roff format. Instead I would prefer to use a tool that converts markdown documents to man pages.

For clevis we are using [ronn](https://rtomayko.github.io/ronn/ronn.1.html) that converts md files to roff and html. It's not only easier for human beings to write markdown but also integrates nicely with Github so you don't need to duplicate the doc for people navigating the project and the man pages installed.

**Comment by williamcroberts** [comment]
This sounds wonderful, I wanted to use markdown but didn't know of any tool to do the conversion. Is there a markdown WYSIWYG editor or any editor you use? I'm not particularly fluent in markdown (or troff either).

**Comment by martinezjavier** [comment]
@williamcroberts I don't know about a WYSIWYG one, but I'm using [retext](https://github.com/retext-project/retext) and is pretty decent. It has a live preview feature which makes easier to see how it would look like.

I'm also not that fluent in markdown but I know the basics, it's a much more intuitive format for human beings than troff.

**Comment by liuqun** [comment]
Doxygen reads markdown text from C/C++ comments, then coverts them into html and unix man pages:

Here is an example from Infineon's TPM2.0 eltt2:
```
// this is the main page for doxygen documentation.
/** @mainpage   Infineon Embedded Linux TPM Toolbox 2 (ELTT2) for TPM 2.0 Documentation
  *
  * @section    Welcome
  * Welcome to Infineon TPM 2.0 Software-Tool "Embedded Linux TPM Toolbox 2 (ELTT2)".\n
  * \n
  * @section    Introduction
  * ELTT2 is a single file-executable program
  * intended for test, diagnosis and basic state changes of the Infineon
  * Technologies TPM 2.0.\n
  * \n
  * @section    Copyright
  * Copyright (c) 2014, Infineon Technologies AG\n
  * All rights reserved.\n
  * ...
  */
```
https://github.com/Infineon/eltt2/blob/c248520926e1a037ffe0434480e56073d49c993b/eltt2.h#L30

**Comment by williamcroberts** [comment]
@martinezjavier I used ronn this weekend getting the manpage together for tpm2_pcrevent. While ronn -m worked, ronn -r would not produce valid troff. Looking at the latest version 0.73, it's over 7 years old. I don't want to use anything that isn't very current.

**Comment by martinezjavier** [comment]
@williamcroberts oh, I didn't notice that it was so old... I just looked and they have a bunch of PR opened since 2010 :disappointed: 

I didn't have issues on Clevis but probably the man pages are more simpler than the tpm2-tools ones. So yeah, I agree with you that a current / maintainer tool should be used instead.

**Comment by williamcroberts** [comment]
@martinezjavier PR #429 is using a ruby gem called md2man-roff: https://rubygems.org/gems/md2man/versions/5.1.1

This seems to be more recent than ronn and is working for the tpm2_pcrevent manpage.

**Comment by martinezjavier** [comment]
@williamcroberts awesome, I'll find some time this to convert the tools man pages (or at least some of them) to markdown then.

**Comment by williamcroberts** [comment]
@martinezjavier , I like how github now renders the man pages when you view them. The only downside is the common bits i'm still injecting with sed, so those would be missing.

**Comment by williamcroberts** [comment]
The manual top level file was deleted it: https://github.com/01org/tpm2-tools/commit/c9b3d9a34aec1d16520d174dac275e69302ed53b

**Comment by liuqun** [comment]
https://github.com/01org/tpm2-tools/wiki need update: https://github.com/01org/tpm2-tools/issues/438

**Comment by martinezjavier** [comment]
@williamcroberts what else is missing to close this issue?

**Comment by williamcroberts** [comment]
@martinezjavier I don't think there is anything. The manual is gone. Eventually we should make the wiki better.

**Comment by martinezjavier** [comment]
@williamcroberts Ok, I just wanted to be sure before doing it, closing now then.
