### ISSUE TITLE
Outdated documents still refers to the legacy resourcemgr, which has been deprecated

### ISSUE THREAD

**Issue by liuqun** [01org/tpm2-tools#392]
https://github.com/01org/tpm2-tools/blob/master/manual#L17 says:
> Launch resourcemgr daemon:
> $ resourcemgr
> or
> $ resourcemgr -sim -tpmhost <ip>

Search keyword `resourcemgr` in this repository, to see more details referring to it:
https://github.com/01org/tpm2-tools/search?utf8=%E2%9C%93&q=resourcemgr&type=

Maybe someone could write a guidebook to help pople replace their legacy resourcemgr with the new tcti-abrmd daemon. Thanks very much.

**Comment by martinezjavier** [comment]
@liuqun, this is a duplication of issue #366 "Update and improve the manual doc"

**Comment by liuqun** [comment]
Thank you
