### ISSUE TITLE
TSS versions

### ISSUE THREAD

**Issue by flihp** [01org/tpm2-tools#406]
I've been working on some stuff in the tabrmd that has run afoul of some upstream API / ABI breaks between the 1.x TSS releases and the current master branch (specifically the ABI break in https://github.com/01org/tpm2-tss/commit/75e6cb7d5dd7222e6fa27ce0fc264de50052383f.

The most 'sane' thing I could come up with quickly was to use the 1.x branch for tabrmd in travis etc. This seemed like the most reasonable thing to do since the tabrmd is making releases from it's master branch. This approach however requires cooperation from the tools in that we'd have to do the same thing here.

Thoughts / alternatives?

**Comment by flihp** [comment]
From a quick first look the tools relies on some of the changes that have been made recently to the TSS headers that have not yet been released. My proposal above (track the 1.x branch) would require picking these into the 1.x branch which may not be possible if they break backward compatibility (first glance doesn't look like they do however).

**Comment by williamcroberts** [comment]
I think what you would want to do is create a branch off your 1.1.0 tag and then place changes on there that you want to release against some specific version of dependencies. Your yaml file for travis would be different from master, in that it would specify the versions of dependencies.

master should be tracking the master or next major tss release so we can find any issues introduced in master ASAP. I actually found issues in the marshaling code.

**Comment by tstruk** [comment]
On 08/15/2017 11:03 AM, Philip Tricca wrote:
> I've been working on some stuff in the tabrmd that has run afoul of some upstream API / ABI breaks between the 1.x TSS releases and the current master branch (specifically the ABI break in 01org/tpm2-tss@75e6cb7 <https://github.com/01org/tpm2-tss/commit/75e6cb7d5dd7222e6fa27ce0fc264de50052383f>.
> 
> The most 'sane' thing I could come up with quickly was to use the 1.x branch for tabrmd in travis etc. This seemed like the most reasonable thing to do since the tabrmd is making releases from it's master branch. This approach however requires cooperation from the tools in that we'd have to do the same thing here.
> 
> Thoughts / alternatives?
> 

I fail to see how the 01org/tpm2-tss@75e6cb7 brakes ABI.
Even though these were UINT32 they were marshaled as UINT8.
The final TPM command should look the same before and after
this change.
Thanks,
-- 
Tadeusz

**Comment by flihp** [comment]
I've been trying to keep from creating a long-lived release branch that will have only one commit difference from the master branch. I get your point though: having master branches tracking upstream master keeps the surprises to a minimum and get the upstream better testing.

I'm still kinda torn on this though. @tstruk do you have any opinions? I figure this decision will have an impact on the release process for the projects involved (no releases from master branches?) so we should get everyone to weigh in.

**Comment by flihp** [comment]
you beat me by a second :smile: 

sizeof (TPMA_SESSION) was changed by that commit. Maybe I'm using ABI inappropriately here but the end result was the tabrmd code that parses the auth area of a command had to change on account of this.

**Comment by tstruk** [comment]
On 08/15/2017 11:29 AM, Philip Tricca wrote:
> you beat me by a second 😄
> 
> sizeof (TPMA_SESSION) was changed by that commit. Maybe I'm using ABI inappropriately here but the end result was the tabrmd code that parses the auth area of a command had to change on account of this.
> 

Well, 01org/tpm2-tss@75e6cb7 changed sizeof (TPMA_SESSION.val). The sizeof (TPMA_SESSION) should be the same.
See https://github.com/01org/tpm2-tss/commit/49f9d1573855ad1a6864560a9227fe5c9a0188c2.
This is not an ideal solution, but maybe this can be used to make the tss_1.1 compatible with abrmd?

**Comment by flihp** [comment]
It's less about keeping the 1.x branch compatible with the tabrmd and more about maintaining compatibility for *all* users. I'd be very hesitant to change the size of a type and calling it backward compatible.

Back to the question at hand though: with the way we've been having the master branch of the tools / tabrmd tracking the master branch of the tss we've set up a situation where the tabrmd / tools *must* have release branches tied to a stable release of the tss. I broke this model in the tabrmd (by having master track the 1.x branch instead of master from the tss) and it broke the tools build. I don't object to Bills proposal, just want to be sure you've seen this in case you have an opinion?

**Comment by williamcroberts** [comment]
For one, just becuase you branch doesn't mean that branch is only going to have 1 to 2 commits, you could push most of your changes to your release branch and merge that back to master, while incompatible changes with respect to the release are resident on master. This is how some projects I have worked on do it, namely Android. Master moves ahead while stable branches move, and occasionally stable is merged into master, or cherry-picked between branches as necessary.

**Comment by martinezjavier** [comment]
@flihp @williamcroberts  since [tpm2-tss 1.2.0-rc0](https://github.com/01org/tpm2-tss/releases/tag/1.2.0_rc0) was released, I guess that means this issue can be closed now?

**Comment by williamcroberts** [comment]
@martinezjavier not quite, as were discussing the master branch of tabrmd and what version of tss we should be using during CI and master branch work flows.

**Comment by martinezjavier** [comment]
@williamcroberts ah, Ok. Sorry for the confusion then.

**Comment by flihp** [comment]
The next release of the tabrmd has an RC posted (finally). My plan is to get that release done before updating the master branch to track the master branch of the TSS. I'm planning some changes for tabrmd that will not be backward compatible anyways so tabrmd master will turn into a 2.x release (tracking TSS master) while a 1.x branch (tracking TSS 1.x) will be created from the 1.1.1 release tag.

Sound good?

**Comment by martinezjavier** [comment]
So what's the plan for tpm2-tools travis CI until the tpm2-abrmd version is released and its master branch is updated to track the TSS master branch?

The travis CI now is broken due tpm2-abrmd master needing to be built against TSS 1.x branch, i, e:

https://travis-ci.org/01org/tpm2-tools/jobs/266775607

But the travis.yml can't just be changed to build TSS 1.x branch instead since tpm2-tools master needs TSS master to build...

Or did I misunderstand something from this conversation?

**Comment by williamcroberts** [comment]
@martinezjavier that's pretty much where we are at, im hoping to have patches that at least get abrmd building/working until its updated properly to the master tss branch. Things suitable for upstreaming ill submit PRs and things that are hacky ill just git apply in the travis.yml file.

**Comment by williamcroberts** [comment]
This PR fixes it for me: https://github.com/01org/tpm2-abrmd/pull/151

**Comment by martinezjavier** [comment]
@williamcroberts cool, I also proposed a PR with the first fix but didn't dig further for the other ones.
