### ISSUE TITLE
No tools are available for Hash/HMAC/Event Sequences

### ISSUE THREAD

**Issue by liuqun** [01org/tpm2-tools#422]
There isn't any tool that uses the following Hash, HMAC, or event sequences API:
1. Hash sequences commands:
 Tss2_Sys_HashSequenceStart() / Tss2_Sys_SequenceUpdate() / Tss2_Sys_SequenceComplete()
1. HMAC sequences commands:
 Tss2_Sys_HMAC_Start() / Tss2_Sys_SequenceUpdate() / Tss2_Sys_SequenceComplete()
1. Event sequences commands:
 Tss2_Sys_HashSequenceStart() / Tss2_Sys_SequenceUpdate() / Tss2_Sys_EventSequenceComplete()

In my opinion, we may improve the existing tools by introducing sequences commands.
- An enhanced version of "**tpm2_hash**" to support any input file larger than 1024 bytes.
- An enhanced version of "**tpm2_hmac**" to support any input file as well.
- A simple version of "**tpm2_pcrevent**" that uses single Tss2_Sys_PCR_Event() command to handle with data within 1024 bytes. ("**tpm2_pcrextend**" requires an existing hash digest, while "tpm2_pcrevent" doesn't.)
- An enhanced version of "tpm2_pcrevent" which uses the event sequences to handle larger files.

**Comment by williamcroberts** [comment]
You could just make the existing tools smart enough to handle files bigger than 1024 bytes, like how nvread and nvwrite were just fixed. As far as tpm2_pcrevent, that should be a separate tool from extend.

**Comment by williamcroberts** [comment]
I updated hash on PR #424. The only downside, is that when a file is < 1024 bytes, there is 3 call outs to the TPM. However, handling stdin when it was a fifo and unknown file size was important to me. We could optimize that later if need be and detect when seek() fails on the fifo (illegal seek).

**Comment by williamcroberts** [comment]
For tpm2_pcrevent, I have that started, but the sequencing is throwing an error "TPM_RC_AUTH_MISSING" on the Tss2_Sys_EventSequenceComplete call.

See:
https://github.com/williamcroberts/tpm2.0-tools/tree/tpm2_pcrevent

**Comment by williamcroberts** [comment]
Ahh I figured it out. TPM2_SequenceComplete has @ on both pcrHandle and sequenceHandle. Per the spec, @ is a decorator that "indicates that an authorization session is required for use of the entity associated with the handle.". Thus for the SequenceComplete, one needs to specify 2 entries to the command auths array.

**Comment by liuqun** [comment]
When and why should we do swap_auths() for such 2 entries?

**Comment by williamcroberts** [comment]
The order matters, and at most we need 2.
SequenceUpdate() requires that index 0 of the auths be for the sequenceHandle.
EventSequenceComplete() requires that index 0 be for the pcrIndex and index 1 for the sequenceHandle.

If those commands just kept the order consistent, we would have just been able to manipulate the size field.
