### ISSUE TITLE
Make a symbol link "tpm2_listpcrs" during "make install" for backward compatibility

### ISSUE THREAD

**Issue by liuqun** [01org/tpm2-tools#438]
The legacy tpm2_listpcrs should be supported (even if it was renamed to tpm2_pcrlist) because:

1. There are so many stuffs that were still refering to tpm2_listpcrs, such as: https://github.com/01org/tpm2-tools/wiki/How-to-use-tpm2-tools
2. Linux distros are still providing stable version of tpm2-tool which carried with tpm2_listpcrs
3. By the way, there is another tool named tpm2_listpersistert, which begins with "tpm2_list"

**Comment by martinezjavier** [comment]
@liuqun although I agree with you that backward compatibility is very important, @williamcroberts made a decision to change the tool name and so I don't think that's the project responsibility to attempt maintaining it.

This will be a major release and there are other changes that will break backward compat anyways.

1. I agree that the docs should be fixed to reflect the latest development.
2. That's correct, and distros should make sure that a package for a new version Replaces / Obsoletes the old one.
3. I'll let @williamcroberts comment on this, I don't have a strong opinion on the tools names.

**Comment by liuqun** [comment]
Thanks very much @martinezjavier !

**Comment by martinezjavier** [comment]
@liuqun @williamcroberts I guess we can close this issue now?

**Comment by liuqun** [comment]
the wiki page needs update: @williamcroberts 
https://github.com/01org/tpm2-tools/wiki/How-to-use-tpm2-tools

**Comment by williamcroberts** [comment]
Updated to change listpcrs to pcrlist on wiki.
