### ISSUE TITLE
Add official wiki URL reference into README.md

### ISSUE THREAD

**Issue by liuqun** [01org/tpm2-tools#440]
Please consider adding the wiki page reference of https://github.com/01org/tpm2-tools/wiki  into README.md, and open github wiki page co-edit permitions to project contributors.

See also: #366

**Comment by martinezjavier** [comment]
@liuqun agreed, I think this would also will make issues like #434 less likely to be filled.

**Comment by liuqun** [comment]
@martinezjavier What about adding an FAQ among these wiki pages?

**Comment by martinezjavier** [comment]
@liuqun sounds good to me, the more docs the better IMHO :smiley: (as long as we keep them updated)

**Comment by williamcroberts** [comment]
Unfortunately I cannot use the built-in permission system in Github. However, I can do something like this:
1. Ill create a tpm2-tools-wiki project
2. You fork that
3. Submit PRs to the wiki project
4. Ill pull them into that when approved
5. Ill push that into the tpm2-tools wiki
