### ISSUE TITLE
Removed -I parameter in tpm2_hash - man pages need to be updated

### ISSUE THREAD

**Issue by rtkypoeluev** [01org/tpm2-tools#441]
Just noticed that tpm2_hash doesn't support "-I" option.
Man pages for tpm2_hash need to be updated.

Example:
   tpm2_hash -H e -g 0x00B -I message.txt -o hash.bin -t ticket.bin
   ERROR: Unknown Argument: I

(skipping -I, just leaving message.txt does the trick)

**Comment by williamcroberts** [comment]
You can even:
```
echo -n "foo" | tpm2_hash
tpm2_hash <<< "foo"
tpm2_hash < file
tpm2_hash file
```

Also for your above command, you can now do -g sha256 to avoid memorizing algorithm ids.

**Comment by liuqun** [comment]
Can we provide a separate tool named tpm2_sha256sum(or "tpm2 sha256sum") that behaves just the same /usr/bin/sha256sum

**Comment by liuqun** [comment]
By the way, 3rd party authors are still using tpm2_hash with -I option...
See:
https://dguerriblog.wordpress.com/2016/03/03/tpm2-0-and-openssl-on-linux-2/
![image](https://user-images.githubusercontent.com/64795/29903828-8d28db82-8e38-11e7-8ace-a2ec933abc68.png)

**Comment by martinezjavier** [comment]
@liuqun yes, but as mentioned in another thread there will be changes in the new release that will not be backward compatible.

Having said that, I do hope that things get ironed out on this release and we can maintain it from now on. I do agree with you that not breaking users on each release its very important.

BTW, it seems the procedure explained by @dguerri in his post will not be needed anymore after @mgerstner PR #427 (Improve interoperability with OpenSSL) is merged.

**Comment by martinezjavier** [comment]
@rtkypoeluev I don't see the -I being mentioned in the tpm2_hash man page anymore.

And also I see that the man page was correctly updated on commit 6388831d0fa3 ("tpm2_hash: drop -I option"). Are you sure you are looking at the last version?

**Comment by martinezjavier** [comment]
@rtkypoeluev sorry, it seems I'm blind. On a second read I noticed that the man page example wasn't updated. I've created PR #443

**Comment by rtkypoeluev** [comment]
No worries :), thanks for taking care of it!

**Comment by williamcroberts** [comment]
Theres a lot in this thread:
1. I'm not two worried about breaking options if it makes things easier, however, they will only be for major releases. We can do any minor releases for things people want, if they backport them to the stable branch.
2. Folks using -I on hash, well that's also from 2016
3. For tpm2_hash to behave like shasum, just modify the file list, it currently only takes one file, make it take many and update the output.

With that said, I am hoping to get most of the options ironed out for the 3.0 release, so hopefully less churn from there on out.
