### ISSUE TITLE
Failed To Initialize TCTI Context: 0x1 

### ISSUE THREAD

**Issue by HaydonC** [01org/tpm2-tools#444]
I previously set up the following system:

Ubuntu 16.04 ( kernel 4.12 ) + Latest 2.X tpm2-tools + Latest 1.x tpm2-tss

And had the whole system work correctly [though interestingly if I sudo'd a command it would have an issue]

However I then swapped my setup to a 4.4 kernel and (as the wiki section shows) installed the latest tpm2-abrmd and when trying to run any tpm command with this setup I encounter the 'failed to initialize TCTI context: 0x1'.

A strace of the above led me to believe it was trying to connect to a simulator instead to I ran a command with '-T device' following and a further strace showed the line:

'open("/dev/tpm0", 0_RDWR) = -1 EBUSY (Device or resource busy)'

**Comment by HaydonC** [comment]
Having noticed the 'tpm2-resourcecmgr' daemon was running I killed this process and the above error disappears. The TPM seems to pass around 50% of the tests in the 'test_all.sh' script.
Is this the write way to be going around this?

**Comment by martinezjavier** [comment]
@HaydonC its a known issue that some tests fail with a real TPM2, these have hardcoded assumptions that are only true for the TPM2 simulator used in the CI. See issue #335.

Now, 50% it's a lot. Can you please share the tests that fail and the log output?

**Comment by williamcroberts** [comment]
In fact you need version 2.X or be using master
https://github.com/01org/tpm2-tools/tree/2.X

**Comment by williamcroberts** [comment]
Disregard my previous comments, I see you posted the versions at the top. I'm assuming abrmd is running against the actual tpm, is that correct?

**Comment by HaydonC** [comment]
Hi guys,
Having some trouble getting the 'test_all.sh' to write output to a file (not sure why..) however the test result shows 10 passed 18 failed. 
Failed tests:
test_tpm2_load.sh
test_tpm2_loadexternal.sh
test_tpm2_evictcontrol.sh
test_tpm2_quote.sh
test_tpm2_unseal.sh
test_tpm2_certify.sh
test_tpm2_evictcontrol.sh (NOTE: this is tested twice?)
test_tpm2_getpubek.sh
test_tpm2_getpubak.sh
test_tpm2_makecredential.sh
test_tpm2_activecredential.sh
test_tpm2_readpublic.sh
test_tpm2_rsapublic.sh
test_tpm2_rsaencrypt.sh
test_tpm2_rsadecrypt.sh
test_tpm2_encryptdecrypt.sh
test_tpm2_sign.sh
test_tpm2_verifysignature.sh

**Comment by HaydonC** [comment]
@williamcroberts it was the resourcemgr that had tpm0 open already. Strange thing is that once I 'systemctl stop tpm2-resourcecmgr' I am able to run the tpm2-tool commands? (I even went as far as uninstalling tpm2-abrmd and it still worked?)
Note: that this meant tpm2-tools 2.X and tpm2-tss 1.x working on Linux kernel 4.4 without abrmd being installed?

**Comment by martinezjavier** [comment]
@HaydonC you can redirect both the standard output and standard error streams to a file using this command:

```
cd test/system
$ ./test_all.sh > /foo/bar.log 2>&1
```

**Comment by martinezjavier** [comment]
@HaydonC it will work if you are using the device TCTI (i.e: setting TPM2TOOLS_TCTI_NAME and TPM2TOOLS_DEVICE_FILE env vars or the --tcti and --device-file common options).

**Comment by HaydonC** [comment]
@martinezjavier I have been using the '>' to redirect the output of the tests but it won't write to a file. Individual tests will. I'll write a quick script to get around this..

**Comment by HaydonC** [comment]
[testlog.txt](https://github.com/01org/tpm2-tools/files/1270015/testlog.txt)

Logs from the failed tests...

**Comment by martinezjavier** [comment]
@HaydonC Ok. First a debug tip, you can use the tpm2_rc_decode tool to decode the TPM errors. I see that in all cases the error is 0x902:

```
$ tpm2_rc_decode 0x902
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 0 warning code
  hex: 0x02
  name: TPM_RC_OBJECT_MEMORY
  description: out of memory for object contexts
```

So the error is TPM_RC_OBJECT_MEMORY which means that the TPM ran out of space for transient objects. The TPM only can store a small set of objects at any given time. You can check the number for your TPM with:

```
$ tpm2_dump_capability --cap=properties-fixed | grep TRA
TPM_PT_HR_TRANSIENT_MIN:    0x00000003
```

That's what the resource manager is used for, so the objects can be swapped out and in from the TPM. Are you sure you are using the resource manager and not accessing the TPM2 directly?

**Comment by martinezjavier** [comment]
@HaydonC I'm pretty sure your problem is that you are sending commands to the TPM directly instead of using the RM. But still when trying to reproduce your issue I found two bugs in the tests and fixed on PR #449.

**Comment by liuqun** [comment]
@HaydonC As I know, on a real TPM2.0 device some commands such as TPM2_EncryptDecrypt are not available, while on a PC with Microsoft Simulator.exe every command is available.

**Comment by HaydonC** [comment]
@martinezjavier I think you're right, what should 'TPM2TOOLS_DEVICE_FILE' be set to in this situation?

**Comment by martinezjavier** [comment]
@HaydonC it doesn't have to be set, in fact no TPM2TOOLS_* env var should be set if you are using the tpm2-abrmd resource manager. It's the default.

Make sure that support for it was built though, check if configure did report:

```
checking for TCTI_TABRMD... yes
```

**Comment by martinezjavier** [comment]
@HaydonC it's also worth checking if you are executing a binaries that are dynamically linked to the TCTI tabrmd library (for example sometimes I forget to pass a proper --prefix to configure and use outdated/wrong binaries by mistake)

```
$ ldd $(which tpm2_pcrlist) | grep abrmd
        libtcti-tabrmd.so.0 => /lib64/libtcti-tabrmd.so.0 (0x00007f68ff1f1000)
```

**Comment by williamcroberts** [comment]
@HaydonC it sounds like device is somehow your default tcti then. Perhaps configure isn't finding abrmd tcti. Perhaps try configure --without-tcti-device --without-tct-socket this way if it doesn't find abrmd it will fail hard.

**Comment by HaydonC** [comment]
So having uninstalled tpm2-tools and killed tpm2-resourcemgr, tpm2_listpcrcs still works (with all env variables having been deleted as well). This whole thing has confused me too much so I'm going to try a fresh Ubuntu install.

**Comment by martinezjavier** [comment]
@HaydonC can you share your configure output and config.log?

Also please test what @williamcroberts said.

**Comment by martinezjavier** [comment]
@HaydonC but from what you mention in your last comment, it seems that the problem is what I mentioned before (some old binaries being in your $PATH but no the ones that you want).

**Comment by martinezjavier** [comment]
last comment, please close this issue and move the discussion to tpm2@lists.01.org instead. It seems the problem is related to your setup and not a bug in tpm2-tools.

**Comment by HaydonC** [comment]
Yeah, apologies for posting here! Thanks again
