### ISSUE TITLE
configure doesn't detect missing md2man-roff

### ISSUE THREAD

**Issue by flihp** [01org/tpm2-tools#445]
It's a minor inconvenience but detecting this stuff @ configure time is pretty simple. I'm working up a PR now.

**Comment by williamcroberts** [comment]
Ahh yeah, good call.

**Comment by flihp** [comment]
PR is up in #447, took me a while to set up my new fedora system though. I haven't used `rpm` / `yum` in a long time :smile:

**Comment by martinezjavier** [comment]
@flihp It's seems is a long time indeed since yum hasn't been the default Fedora package manager for at least 5 years :smiley:

**Comment by williamcroberts** [comment]
Fixed in #448

**Comment by flihp** [comment]
Well I'm glad you guys kept `yum` around for me @martinezjavier :sweat_smile:
