### ISSUE TITLE
Add a PyYAML dependency

### ISSUE THREAD

**Issue by martinezjavier** [01org/tpm2-tools#450]
The tpm2_pcrevent.sh test has a Python helper script that uses the PyYAML module, but that dependency isn't present in autotools and so the test fails when trying to execute after everything builds correctly:

```
$ ./test_tpm2_pcrevent.sh 
Traceback (most recent call last):
  File "./yaml_get.py", line 35, in <module>
    import yaml
ImportError: No module named yaml
old_pcr_value=`./yaml_get.py sha1 9 $yaml_out_file` on line 74 failed: 1
```

```
$ sudo dnf install PyYAML

$ ./test_tpm2_pcrevent.sh 
tpm2_pcrevent succeed
```

**Comment by williamcroberts** [comment]
There's no bash dependency nor python check either for that matter.

**Comment by martinezjavier** [comment]
@williamcroberts I think checking for python as well (and having it as a BuildRequires dependency in the RPM package) makes sense.

**Comment by williamcroberts** [comment]
We can just warn that runing the system tests will fail as well, similar to the md2man check

**Comment by martinezjavier** [comment]
@williamcroberts agreed.
