### ISSUE TITLE
tpm2_zgen_2phase input parameter, inQsB 

### ISSUE THREAD

**Issue by aqinwenky** [01org/tpm2-tools#460]
how to get the inQsB parameter?
I have created the static key in another TPM device and get the public key , which is TPM2B_PUBLIC. 
After run the tpm2_zgen_2phase command, it will get the error 0x1e7.

**Comment by williamcroberts** [comment]
We don't have this command: tpm2_zgen_2phase, but you can use tpm2_rc_decode to decode your error code.

**Comment by aqinwenky** [comment]
@williamcroberts  thanks a lot. I have used tpm2_rc_decode to decode the error code and showed that TPM_RC_ECC_POINT which means the input point inQsB is not on the required curve.  Actually, I  don't know how to get the TPM2B_ECC_POINT inQsB, and I replaced it with public key which is created by tpm2_create. Obviously it's wrong. So do you know how to get the input parameter inQsB？

**Comment by aqinwenky** [comment]
I have solved this problem. The main reason is that I didn't understand the TPM2B_PUBLIC very well.

**Comment by williamcroberts** [comment]
@aqinwenky Can you describe your solution to the problem so we have an archive of it?

**Comment by aqinwenky** [comment]
OK, In the implementation of tpm2_zgen_2phase,  I got in a  trouble which was how could I get the input parameter  inQsB.  According to the specification, I got the public key inQsB by tpm2_create from another TPM device. But it was TPM2B_PUBLIC, so I had to get the TPM2B_ECC_POINT from the TPM2B_PUBLIC.  By reading the second part of the specification, I have found the solution:

    TPM2B_ECC_POINT inQsB;
    TPM2B_PUBLIC inQsbPub;
    UINT16 size;
    memset(&inQsbPub, 0, sizeof(TPM2B_ECC_POINT));
    memset(&inQsB, 0, sizeof(TPM2B_ECC_POINT));
    case 'I':
            size = sizeof(inQsbPub);
            if(loadDataFromFile(optarg, (UINT8 *)&inQsbPub, &size) !=0)
            {
                   returnVal = -5;
                break;
            }
            inQsB.t.point.x = inQsbPub.t.publicArea.unique.ecc.x;
            inQsB.t.point.y = inQsbPub.t.publicArea.unique.ecc.y;
            I_flag = 1;
            break;
