### ISSUE TITLE
TPM2B_INIT(xsize) conflicts to existing micro in tpm2-tss<=1.2.0

### ISSUE THREAD

**Issue by liuqun** [01org/tpm2-tools#468]
https://github.com/01org/tpm2-tools/blob/b410e7f4a4a0d0af8623175654384ec2e0fafa31/lib/tpm2_util.h#L44

is conflicting to:
https://github.com/01org/tpm2-tss/blob/1.2.0/include/sapi/tpmb.h#L75 
```
#define TPM2B_INIT(TYPE, name)					\
    TPM2B_##TYPE    name = {sizeof(name.t.buffer), {0}}
```
This made it impossible for me to build tpm2-tools against tpm2-tss release 1.2.0

Note: In tpm2-tss master branch, "TPM2B_INIT(TYPE, name)" has been removed since 2017-8-15, see https://github.com/01org/tpm2-tss/commit/a3b6e1d54b1005d2e8148609b88955ed3dc4891c

**Comment by martinezjavier** [comment]
@liuqun tpm2-tools master isn't supposed to be used with tpm2-tss 1.2.0 (only with master). The that that list the the tpm2-tools -> tpm2-tss version compatibilities can be found in [this wiki page](https://github.com/01org/tpm2-tools/wiki)

**Comment by liuqun** [comment]
I see in the table only tpm2-tools branch 2.x is compatible with tpm2-tss 1.2.0
Other people might be confused, when we told them the 2.x release of tpm2-tools is NOT yet compatible with master branch of tpm2-tss.

---

https://github.com/01org/tpm2-tools/wiki

| tpm2-tools version | tpm2-tss version | tpm2-abrmd version|
|--------------------|------------------|-------------------|
|[2.1.0](https://github.com/01org/tpm2-tools/releases/tag/2.1.0)|[1.2.0](https://github.com/01org/tpm2-tss/releases/tag/1.2.0)|[1.1.1](https://github.com/01org/tpm2-abrmd/releases/tag/1.1.1)|
|[df751ae](https://github.com/01org/tpm2.0-tools/tree/df751ae5bea0bb057c9ee4cb0c1176c48ff68492)(master)|[1.1.0](https://github.com/01org/TPM2.0-TSS/releases/tag/1.1.0)|[1.0.0](https://github.com/01org/tpm2-abrmd/releases/tag/1.0.0)|
|[v2.0.0](https://github.com/01org/tpm2.0-tools/releases/tag/2.0.0)|[1.0](https://github.com/01org/TPM2.0-TSS/releases/tag/1.0)|old resourcemgr|
|[v1.1.0](https://github.com/01org/tpm2.0-tools/releases/tag/v1.1.0)|[1.0](https://github.com/01org/TPM2.0-TSS/releases/tag/1.0)|old resourcemgr|
|[v1.1-beta_1](https://github.com/01org/tpm2.0-tools/releases/tag/v1.1-beta_1)|[1.0-beta_1](https://github.com/01org/TPM2.0-TSS/releases/tag/1.0-beta_1)|old resourcemgr|
|[v1.1-beta_0](https://github.com/01org/tpm2.0-tools/releases/tag/v1.1-beta_0)|[v1.0-beta_0](https://github.com/01org/TPM2.0-TSS/releases/tag/v1.0-beta_0)|old resourcemgr|
|[14a7ff5](https://github.com/01org/tpm2.0-tools/tree/14a7ff527bc0411c215bd9d575f2866e1f2e71cf)|[210b770](https://github.com/01org/TPM2.0-TSS/tree/210b770c1dff47b11be623e1d1e7ffb02298fca5)|old resourcemgr|
|[4b4cbea](https://github.com/01org/tpm2.0-tools/tree/4b4cbeafe30430f42826592dee2abafec818385f)|[d4f23cc](https://github.com/01org/TPM2.0-TSS/tree/d4f23cc25c4c0fb66dd36897d2fad8e1e37c6443)|old resourcemgr|
|[e8150e4](https://github.com/01org/tpm2.0-tools/tree/e8150e48dd47f761dff10583631b2a0a30ee4d90)|[60ec042](https://github.com/01org/TPM2.0-TSS/tree/60ec04237b5344666435e129bd85f7496a6a9985)|old resourcemgr|
|[84d5f26](https://github.com/01org/tpm2.0-tools/tree/84d5f262f281556c57f7ec2fba06eda3acadd26c)|[371fdbc](https://github.com/01org/TPM2.0-TSS/tree/371fdbc638c55b9ac8a0eaec9375dbca0412861c)|old resourcemgr|
|[v1.0.1](https://github.com/01org/tpm2.0-tools/releases/tag/v1.0.1)|[1.0-alpha_0](https://github.com/01org/TPM2.0-TSS/releases/tag/1.0-alpha_0)|old resourcemgr|

**Comment by martinezjavier** [comment]
@liuqun I believe your conclusions are correct. Feel free to propose a patch to the wiki page table if you think that is not clear enough.

**Comment by williamcroberts** [comment]
I made an edit to the wiki to annotate that tools master is tracking the master of tss and abrmd.
