### ISSUE TITLE
tpm2_getmanufec needs to be ported to password format

### ISSUE THREAD

**Issue by williamcroberts** [01org/tpm2-tools#483]
tpm2_getmanufec is still using the old -X for hex passwords, port over to use the new password specification language and update man page.

**Comment by martinezjavier** [comment]
@williamcroberts this issue was fixed on commit 1115326f81c4 ("tpm2_getmanufec: switch to use tpm2_password_util_from_optarg").

Sorry, I didn't know there was an issue for this or I would had added a Fixes tag.
