### ISSUE TITLE
tpm2_getmanufec - -i instead of -S for Session input

### ISSUE THREAD

**Issue by williamcroberts** [01org/tpm2-tools#484]
For the session handling, use -S consistently. However, in tpm2-getmanufec, -i is used as -S is being used for address. Use -A for tpm server address and change -i to use -S

**Comment by martinezjavier** [comment]
@williamcroberts agreed. Another thing that annoys me is tpm2_create using -o and -O for public/private  section of the object and tpm2_load using -u and -r for the same.

**Comment by idesai** [comment]
agreed. short options are annoying in general :)

**Comment by williamcroberts** [comment]
There is a lot of options that can be fixed up. @idesai We need to go over how we actually want to pass session context `-S <handle>`. Perhaps if -S is specified, we load and save context to a file. Which would indicate to the RM to keep that context around and not flushed. The question is, when do we say were done with it, explicit tpm2_flushcontext call?

We can get the session handle supposedly from the contextsave file.

**Comment by idesai** [comment]
@williamcroberts, this is how i see our tools with the incoming resource manager change:
tpm2_createpolicy(save ctx) --> tpm2_<some tool>(load ctx, close/flush ctx) [default]
                                                 --> tpm2_<some tool>(load ctx, save ctx) [save/continue option]
 Currently the tools treat them as inputs only but once the RM changes kick in, it'll be ideal to have an output option (option to continue the context) in all tools. What do you think?

**Comment by williamcroberts** [comment]
@idesai yes, but I would like -S to be an input output parameter. IIRC, -C or -c  (in most cases) is already present to cause a Tss2_Sys_ContextLoad() call. We would need to make it so it has a Tss2_Sys_ContextSave() call at the end... so this was -S can just be chained...

Im thinking something like this:
```
tpm2_thing1 -S ctx.dat (load - save)
tpm2_thing2 -S ctx.dat (load - save)
tpm2_flushcontext -S ctx.dat (evict from tpm/RM)
```
