### ISSUE TITLE
Ensure that scripts are properly cleaning up their temporary files on exit

### ISSUE THREAD

**Issue by martinezjavier** [01org/tpm2-tools#486]
Some tests create temporary files but don't remove it. These should be cleaned up.

Also, some tests are just removing the temporary files at the end of their execution. So if the script finishes early due some errors (or a user cancels it with a signal), the files are never removed. Instead scripts should define a cleanup function that's set as a trap handler for the EXIT signal.

For an example, see commit 69bd17f53b48 ("test: make sure temp files are cleaned up on test_tpm2_nv.sh exit").

**Comment by williamcroberts** [comment]
This has been opened before, I hacked test_wrapper in test_all.sh to clean things up when test scripts don't, but it's quite a hack. You can likely blame that for the ticket information.

**Comment by martinezjavier** [comment]
@williamcroberts I see, you mean commit f569e46ad20f ("tests: cleanup test artifacts") that fixed issue #125.

**Comment by martinezjavier** [comment]
So we should remove that once all the tests are properly cleaning their temporary files.

**Comment by williamcroberts** [comment]
@martinezjavier yeah that nasty hack should be removed when the tests are doing things correctly.
