### ISSUE TITLE
Creating objects with parent keys using symmetric algorithms doesn't work

### ISSUE THREAD

**Issue by martinezjavier** [01org/tpm2-tools#504]
This works:

```
$ tpm2_createprimary -A o -g sha256 -G ecc -C primary.context                                                                                                              

CreatePrimary Succeed ! Handle: 0x80ffffff              

$ tpm2_create -g sha256 -G keyedhash -u obj.pub -r obj.priv -c primary.context -I- <<< "foobar"
ObjectAttribute: 0x00000052                             

Create Object Succeed !
```

But this doesn't:

```
$ tpm2_createprimary -A o -g sha256 -G symcipher -C primary.context

CreatePrimary Succeed ! Handle: 0x80ffffff

$ tpm2_create -g sha256 -G keyedhash -u obj.pub -r obj.priv -c primary.context -I- <<< "foobar"
ObjectAttribute: 0x00000052
ERROR: 
Create Object Failed ! ErrorCode: 0x18a
```
The error isn't that descriptive:

```
$ tpm2_rc_decode 0x18a
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 1 error code
  hex: 0x0a
  identifier: TPM_RC_TYPE
  description: the type of the value is not appropriate for the use
handle
  hex:0x100
  identifier:  TPM_RC_1
  description:  (null)
```

I couldn't find in the TCG specification anything that says that symmetric keys can't be used as parent keys. Is this a limitation of the tools or something that's not supported by the spec (and I missed) ?

**Comment by webmeister** [comment]
> I couldn't find in the TCG specification anything that says that symmetric keys can't be used as parent keys.

This depends on the version of the specification. Symmetric parent keys are supported by 01.38, but not in older versions like 01.16. I'm not sure where exactly this is defined in the specification, but you can see the difference for example in table 24 in chapter 25.1.5 where for 01.16 it says "In this specification, an asymmetric key with these properties is referred to as a Storage Key." whereas 01.38 drops the word "asymmetric" there: "In this specification, key with these properties is referred to as a Parent Key. Asymmetric keys and symmetric keys with these attributes are Storage Parents"

What spec version does your TPM implement?

**Comment by martinezjavier** [comment]
@webmeister thanks a lot for the explanation. Even after being working with TPM related stuff for a couple of months, I still found hard to navigate through all the specification docs.

My TPM2 implements version 01.16 so that explains why it fails for me then:

```
$ tpm2_dump_capability -c properties-fixed | head -n8
TPM_PT_FAMILY_INDICATOR:
  as UINT32:                0x08322e3000
  as string:                "2.0"
TPM_PT_LEVEL:               0
TPM_PT_REVISION:            1.16
TPM_PT_DAY_OF_YEAR:         0x0000012f
TPM_PT_YEAR:                0x000007de
TPM_PT_MANUFACTURER:        0x494e5443
```
