### ISSUE TITLE
"Context not large enough" problem

### ISSUE THREAD

**Issue by JohnBrown2014** [01org/tpm2-tools#525]
Hello,

I'm trying some basic operations with key creation with simulator but I've encountered problems with that. 

Software versions I have:

tools 2.1.0
tss 1.2.0
abrmd 1.1.1
ibmtpm974

When I give too many options to tpm2_createprimary (for example) the return value is 0x80012, let me show you two examples:

```
jb@debian-buster:~/src/keys$ tpm2_createprimary -A e -K objectpass -g 0x000b -G 0x0001 -C po.ctx
nameAlg = 0x000b
type = 0x0001
contextFile = po.ctx
ERROR:
CreatePrimary Failed ! ErrorCode: 0x80012

jb@debian-buster:~/src/keys$ tpm2_rc_decode 0x80012
error layer
  hex: 0x80000
  identifier: TSS2_SYS_ERROR_LEVEL
  description: Error from the SAPI
base error code
  identifier: TSS2_BASE_RC_INSUFFICIENT_CONTEXT
  description: Context not large enough
```

but when I reduce the number of letters in password to one or no password at all it works:

```
jb@debian-buster:~/src/keys$ tpm2_createprimary -A e -K o -g 0x000b -G 0x0001 -C po.ctx
nameAlg = 0x000b
type = 0x0001
contextFile = po.ctx

CreatePrimary Succeed ! Handle: 0x800000ff
```

This problem can appear also in other commands, I'm giving just an example. 

What can be a reason of that?
Regards,
John

**Comment by williamcroberts** [comment]
Off of master, I cannot reproduce this, so likely a bug somewhere. I am also using the ibmtpm532 locally, I need to update the tools to use the newest.

**Comment by williamcroberts** [comment]
Also make sure that you don't have any other versions installed. We've seen issues where it was building against system headers but using a library in DESTDIR and there wise size mismatches between structures.

**Comment by williamcroberts** [comment]
This question is better asked on out mailing list

**Comment by JohnBrown2014** [comment]
Sorry, i'll use mailing list next time. Now I would only like to confirm, that you were right. I had some mess in compiled/installed versions. So did a second try on a clean virtual machine and there were no such problems. Thank you.
