### ISSUE TITLE
create release tarballs

### ISSUE THREAD

**Issue by cardoe** [01org/tpm2-tools#554]
Currently there are no release tarballs built with `make dist` available. This means that the bootstrap script must always be run to build this and this is not very distro friendly as it increases the amount of dependencies required to build this package (all the autotools bits). tpm2-tss already provides `make dist` tarballs so can this project as well?

**Comment by williamcroberts** [comment]
Starting with versions 2.1.1 this will be done. This is documented on the release processes on master. Ill make a similar change on 2.X branch.
