### ISSUE TITLE
Deprecate EncryptDecrypt, use EncryptDecrypt2

### ISSUE THREAD

**Issue by flihp** [01org/tpm2-tools#586]
@williamcroberts : not sure how you want to handle the deprecated command. #585 is the least amount of work required to use EncryptDecrypt2 instead of EncryptDecrypt. We may want to rename the whole command to make it clear which underlying TPM2 command will be invoked. We may also want to leave the existing use of EncryptDecrypt in place since some may have TPM devices that don't support the new command.

**Comment by martinezjavier** [comment]
@flihp instead of changing tpm2_encryptdecrypt to use the new Tss2_Sys_EncryptDecrypt2 function, I would add a new tpm2_encryptdecrypt2 command. Since as you said it may be possible that someone is forced to use EncryptDecrypt due their TPM not supporting EncryptDecrypt2.

**Comment by flihp** [comment]
Looks like doing the right thing here may require the most work :(

**Comment by flihp** [comment]
We should be able to share 99% of the code between the two tools though.

**Comment by martinezjavier** [comment]
Yeah, since the only difference is the SAPI function called as you shown in your commit.

**Comment by williamcroberts** [comment]
Can't we just try version 2 if it fails due to not supported try version 1. I'd like, when and where possible make the tools smarter rather than the user.

**Comment by flihp** [comment]
I'm fine with that approach. It's a question of design goals for sure and I'm happy to have the tools "do the right thing" in these situations. Eventually I'd recommend we phase out the use of the deprecated `EncryptDecrypt` function entirely but I don't think we need to do that immediately.

**Comment by williamcroberts** [comment]
Fixed: #593
