### ISSUE TITLE
upgrade TPM2 simulator

### ISSUE THREAD

**Issue by flihp** [01org/tpm2-tools#587]
This is required by #586 and #585. The old 532 version doesn't support EncryptDecrypt2.

**Comment by flihp** [comment]
Not as seamless as I wanted it to be. Just switching to the new simulator causes one test: `test_output_formats.sh` to fail with the `TPM2_RC_RETRY` error code. I've handled this in the tpm2-tss test harness by just calling the command again. Since this only happens for a few commands it was pretty low impact. I figure there are a few different ways to do this:
1. retry the command in the tool directly
2. retry execution of the tool in the test harness

The available data on `RC_RETRY` is pretty scarce. It's limited to a single statement in part 2 and 3 of the spec (same in each) that states: 

> the TPM was not able to start the command

and since it's listed in part 3 (commands) as "command independent" it could be returned by any command. In practice I've only ever seen the simulator return it for one of the `TPM2_Create*` commands and so I've only handled it for these in the tpm2-tss test harness. In the tools we may want to create a command wrapper that we use to invoke every TPM2 command to retry when this RC is returned.

Thoughts?

**Comment by martinezjavier** [comment]
@flihp this issue (the TPM2 simulator returning a TPM_RC_RETRY) was already discussed in issue #469.

I don't think there was a conclusion on how to this should be handled. Doing it in the tpm2-tools as you suggest in point (1) makes sense to me, although I wonder if it this is something that is more suitable to be handled in the SAPI or TCTI layers so application writers don't have to be aware of it.

**Comment by flihp** [comment]
Thanks for the pointer @martinezjavier. Missed that one.

**Comment by flihp** [comment]
duplicates #469
