### ISSUE TITLE
-T device:/dev/tpm0 considered invalid

### ISSUE THREAD

**Issue by pohly** [01org/tpm2-tools#603]
https://github.com/01org/tpm2-tools/blob/master/man/common/tcti.md#tcti-options:
```
For the device TCTI, the TPM device file for use by the device TCTI can be specified. The default is /dev/tpm0. Example: -T device:/dev/tpm0
```

This example is getting rejected:
```
# tpm2_getrandom -T device:/dev/tpm0
invalid TCTI, see --help
```

"-T device" without path is accepted.

**Comment by martinezjavier** [comment]
@pohly same comment than in #602. You should check the man page for the tools you are building. Hopefully after 3.X things are not going to break anymore between major versions.

**Comment by pohly** [comment]
Invalid issue, user error...
