### ISSUE TITLE
Add RC decoding for resourcemgr layer error code

### ISSUE THREAD

**Issue by gwei3** [01org/tpm2-tools#83]
Can we do this? The concern might be that the resourcemgr error was not documented in TCG spec and no exported and installed into the system include directory.

**Comment by flihp** [comment]
I don't think understand the question. Can you give me an example?

**Comment by flihp** [comment]
This would be a 2 part issue then: We'd need tpm2_rc_decode to have a mechanism to decode RM error codes, but we'd also need the resourcemgr header installed so we can get access to the error codes from the RM. There's probably some work to be done in defining string tables etc as well but step 1 is getting the RM header installed: https://github.com/01org/TPM2.0-TSS/issues/241

**Comment by williamcroberts** [comment]
Wont Fix

**Comment by martinezjavier** [comment]
@williamcroberts nice to see old issues being cleaned up :smiley:
